services:
  sqlserver:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    image: sqlserver-fts:latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always
networks:
  backend:
    name: backend  
    driver: bridge  