services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
       - "8086:8086"
    environment:
       INFLUXDB_DB: k6     
       INFLUXDB_ADMIN_ENABLED: "true"
       INFLUXDB_ADMIN_USER: admin
       INFLUXDB_ADMIN_PASSWORD: adminpass
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: adminpass
    depends_on:
      - influxdb
networks:
  backend:
    name: backend  
    driver: bridge  